version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    container_name: todays-commit-web
    restart: always
    ports:
      - "5999:5999"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
      - ./alembic:/app/alembic

  postgres:
    image: postgres:15.4
    container_name: todays-commit-db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
