version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    container_name: ggg-server
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    volumes:
      - ./src:/app

  postgres:
    image: postgres:15.4
    container_name: ggg_db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
