"""schema-update

Revision ID: 120c64e92f21
Revises: fed4effc963c
Create Date: 2025-07-16 03:43:16.700002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '120c64e92f21'
down_revision: Union[str, Sequence[str], None] = 'fed4effc963c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('x', sa.Float(), nullable=False))
    op.add_column('place', sa.Column('y', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place', 'y')
    op.drop_column('place', 'x')
    # ### end Alembic commands ###
