"""schema-update

Revision ID: 7c5c5965eed0
Revises: b41de6ba5480
Create Date: 2025-07-18 04:29:04.303600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c5c5965eed0'
down_revision: Union[str, Sequence[str], None] = 'b41de6ba5480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.SmallInteger(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_token_user_id', 'token', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_token_user_id', table_name='token')
    op.drop_table('token')
    # ### end Alembic commands ###
