"""schema-update

Revision ID: b41de6ba5480
Revises: 120c64e92f21
Create Date: 2025-07-18 03:37:06.790743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b41de6ba5480'
down_revision: Union[str, Sequence[str], None] = '120c64e92f21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cell', 'zone_code',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cell', 'zone_code',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
