"""Remove unique constraint from User provider_i

Revision ID: fa336e4938e5
Revises: 7e14ba9f71e8
Create Date: 2025-09-01 12:28:36.290371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa336e4938e5'
down_revision: Union[str, Sequence[str], None] = '7e14ba9f71e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_user_provider_id', table_name='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_user_provider_id', 'user', ['provider', 'provider_id'], unique=False)
    # ### end Alembic commands ###
